import type {
  SiteConfig,
  NavigationItem,
  ProductCategory,
  TitaniumGrade,
  Standard,
  Product,
  Article,
} from '@cnbjti/types'

export const siteConfig: SiteConfig = {
  siteName: 'CNBJTI',
  tagline: 'Baoji Titanium Materials & Custom Processing for Global Buyers',
  email: 'sales@cnbjti.com',
  phone: '+86-917-3456789',
  whatsapp: '+8613912345678',
  address: 'No.88 Titanium Valley Industrial Park, High-Tech Zone',
  city: 'Baoji, Shaanxi',
  country: 'China',
  socialLinks: {
    linkedin: 'https://linkedin.com/company/cnbjti',
  },
}

export const navigation: NavigationItem[] = [
  {
    label: 'Products',
    children: [
      { label: 'Titanium Bar & Rod', href: '/en/products/titanium-bar', icon: 'cylinder' },
      { label: 'Titanium Sheet / Plate / Foil', href: '/en/products/titanium-sheet', icon: 'layers' },
      { label: 'Titanium Tube & Pipe', href: '/en/products/titanium-tube', icon: 'pipe' },
      { label: 'Titanium Wire', href: '/en/products/titanium-wire', icon: 'coil' },
      { label: 'Titanium Forgings', href: '/en/products/titanium-forgings', icon: 'hammer' },
      { label: 'Titanium Fasteners', href: '/en/products/titanium-fasteners', icon: 'bolt' },
      { label: 'Titanium Fittings & Flanges', href: '/en/products/titanium-fittings', icon: 'fitting' },
      { label: 'Titanium Anode & Electrode', href: '/en/products/titanium-anode', icon: 'electrode' },
      { label: 'Sintered Titanium Filter', href: '/en/products/titanium-filter', icon: 'filter' },
      { label: 'CNC Titanium Parts', href: '/en/products/cnc-parts', icon: 'cnc' },
    ],
  },
  { label: 'Grades', href: '/en/grades' },
  { label: 'Standards', href: '/en/standards' },
  { label: 'Processing', href: '/en/processing' },
  { label: 'Industries', href: '/en/industries' },
  { label: 'Resources', href: '/en/resources' },
  { label: 'Quality', href: '/en/quality' },
  { label: 'About', href: '/en/about' },
  { label: 'Contact', href: '/en/contact' },
]

export const productCategories: ProductCategory[] = [
  {
    id: '1',
    slug: 'titanium-bar',
    name: 'Titanium Bar & Rod',
    description: 'Round, square, hexagonal and flat bars in all titanium grades. Cut-to-size available.',
    icon: 'bar',
    productCount: 24,
    image: {
      id: 'm1',
      url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
      alt: 'Titanium Bar & Rod',
      mimeType: 'image/jpeg',
      size: 0,
      filename: 'titanium-bar.jpg',
    },
  },
  {
    id: '2',
    slug: 'titanium-sheet',
    name: 'Titanium Sheet / Plate / Foil',
    description: 'Titanium sheet, plate and foil in standard and custom sizes. Mill finish and polished.',
    icon: 'sheet',
    productCount: 18,
    image: {
      id: 'm2',
      url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80',
      alt: 'Titanium Sheet',
      mimeType: 'image/jpeg',
      size: 0,
      filename: 'titanium-sheet.jpg',
    },
  },
  {
    id: '3',
    slug: 'titanium-tube',
    name: 'Titanium Tube & Pipe',
    description: 'Seamless and welded titanium tubes and pipes for industrial and medical applications.',
    icon: 'tube',
    productCount: 16,
    image: {
      id: 'm3',
      url: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&q=80',
      alt: 'Titanium Tube',
      mimeType: 'image/jpeg',
      size: 0,
      filename: 'titanium-tube.jpg',
    },
  },
  {
    id: '4',
    slug: 'titanium-wire',
    name: 'Titanium Wire',
    description: 'Titanium wire for welding, medical devices, aerospace and industrial applications.',
    icon: 'wire',
    productCount: 10,
    image: {
      id: 'm4',
      url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80',
      alt: 'Titanium Wire',
      mimeType: 'image/jpeg',
      size: 0,
      filename: 'titanium-wire.jpg',
    },
  },
  {
    id: '5',
    slug: 'titanium-forgings',
    name: 'Titanium Forgings',
    description: 'Custom titanium forgings including discs, rings, blocks and near-net-shape parts.',
    icon: 'forging',
    productCount: 12,
    image: {
      id: 'm5',
      url: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&q=80',
      alt: 'Titanium Forgings',
      mimeType: 'image/jpeg',
      size: 0,
      filename: 'titanium-forgings.jpg',
    },
  },
  {
    id: '6',
    slug: 'titanium-fasteners',
    name: 'Titanium Fasteners',
    description: 'Titanium bolts, nuts, screws, washers and studs. Standard and custom specifications.',
    icon: 'fastener',
    productCount: 20,
    image: {
      id: 'm6',
      url: 'https://images.unsplash.com/photo-1609205807107-2d5e9e5e5e5e?w=600&q=80',
      alt: 'Titanium Fasteners',
      mimeType: 'image/jpeg',
      size: 0,
      filename: 'titanium-fasteners.jpg',
    },
  },
  {
    id: '7',
    slug: 'titanium-fittings',
    name: 'Titanium Fittings & Flanges',
    description: 'Titanium pipe fittings, flanges, elbows, tees and reducers for corrosive environments.',
    icon: 'fitting',
    productCount: 14,
    image: {
      id: 'm7',
      url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=80',
      alt: 'Titanium Fittings',
      mimeType: 'image/jpeg',
      size: 0,
      filename: 'titanium-fittings.jpg',
    },
  },
  {
    id: '8',
    slug: 'cnc-parts',
    name: 'CNC Titanium Parts',
    description: 'Custom CNC machined titanium components from drawings. Tight tolerances, fast turnaround.',
    icon: 'cnc',
    productCount: 8,
    image: {
      id: 'm8',
      url: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&q=80',
      alt: 'CNC Titanium Parts',
      mimeType: 'image/jpeg',
      size: 0,
      filename: 'cnc-parts.jpg',
    },
  },
]

export const titaniumGrades: TitaniumGrade[] = [
  {
    id: 'gr1',
    slug: 'grade-1-titanium',
    name: 'Grade 1 Titanium',
    shortName: 'Gr.1',
    composition: 'Commercially Pure (CP) Ti, lowest oxygen content',
    description: 'Highest purity, best corrosion resistance and formability. Used in chemical processing and marine.',
    tensileStrength: '240 MPa min',
    yieldStrength: '170 MPa min',
    elongation: '24% min',
    density: 4.51,
    applications: ['Chemical processing', 'Marine', 'Desalination', 'Medical implants'],
  },
  {
    id: 'gr2',
    slug: 'grade-2-titanium',
    name: 'Grade 2 Titanium',
    shortName: 'Gr.2',
    composition: 'Commercially Pure (CP) Ti, standard oxygen content',
    description: 'Most widely used CP titanium. Excellent balance of strength, formability and corrosion resistance.',
    tensileStrength: '345 MPa min',
    yieldStrength: '275 MPa min',
    elongation: '20% min',
    density: 4.51,
    applications: ['Chemical processing', 'Aerospace', 'Marine', 'Architecture', 'Medical'],
  },
  {
    id: 'gr5',
    slug: 'grade-5-titanium',
    name: 'Grade 5 / Ti-6Al-4V',
    shortName: 'Gr.5',
    composition: 'Ti-6Al-4V (6% Aluminum, 4% Vanadium)',
    description: 'The most widely used titanium alloy. High strength-to-weight ratio. Aerospace workhorse.',
    tensileStrength: '895 MPa min',
    yieldStrength: '828 MPa min',
    elongation: '10% min',
    density: 4.43,
    applications: ['Aerospace structures', 'Jet engine components', 'Medical implants', 'High-performance automotive'],
  },
  {
    id: 'gr7',
    slug: 'grade-7-titanium',
    name: 'Grade 7 Titanium',
    shortName: 'Gr.7',
    composition: 'CP Ti + 0.12-0.25% Palladium',
    description: 'Best corrosion resistance of all titanium grades. Ideal for highly corrosive environments.',
    tensileStrength: '345 MPa min',
    yieldStrength: '275 MPa min',
    elongation: '20% min',
    density: 4.52,
    applications: ['Chemical processing', 'Desalination', 'Offshore oil & gas', 'Pulp and paper'],
  },
  {
    id: 'gr9',
    slug: 'grade-9-titanium',
    name: 'Grade 9 / Ti-3Al-2.5V',
    shortName: 'Gr.9',
    composition: 'Ti-3Al-2.5V (3% Aluminum, 2.5% Vanadium)',
    description: 'Higher strength than CP grades with good formability. Used in tubing and aerospace.',
    tensileStrength: '620 MPa min',
    yieldStrength: '483 MPa min',
    elongation: '15% min',
    density: 4.48,
    applications: ['Aerospace tubing', 'Hydraulic systems', 'Bicycle frames', 'Sporting goods'],
  },
  {
    id: 'gr23',
    slug: 'grade-23-titanium',
    name: 'Grade 23 / Ti-6Al-4V ELI',
    shortName: 'Gr.23',
    composition: 'Ti-6Al-4V ELI (Extra Low Interstitials)',
    description: 'Medical-grade Ti-6Al-4V with lower oxygen and iron. Superior fracture toughness.',
    tensileStrength: '860 MPa min',
    yieldStrength: '795 MPa min',
    elongation: '10% min',
    density: 4.43,
    applications: ['Orthopedic implants', 'Surgical instruments', 'Dental implants', 'Cardiac devices'],
  },
]

export const standards: Standard[] = [
  {
    id: 's1',
    slug: 'astm-b348',
    code: 'ASTM B348',
    name: 'Standard Specification for Titanium and Titanium Alloy Bar and Billet',
    description: 'Covers titanium and titanium alloy bar and billet for general industrial use.',
    productTypes: ['Bar', 'Billet'],
  },
  {
    id: 's2',
    slug: 'astm-b265',
    code: 'ASTM B265',
    name: 'Standard Specification for Titanium and Titanium Alloy Strip, Sheet, and Plate',
    description: 'Covers titanium and titanium alloy strip, sheet, and plate.',
    productTypes: ['Sheet', 'Plate', 'Strip', 'Foil'],
  },
  {
    id: 's3',
    slug: 'astm-b338',
    code: 'ASTM B338',
    name: 'Standard Specification for Seamless and Welded Titanium and Titanium Alloy Tubes',
    description: 'Covers seamless and welded titanium tubes for condensers and heat exchangers.',
    productTypes: ['Tube', 'Pipe'],
  },
  {
    id: 's4',
    slug: 'astm-b381',
    code: 'ASTM B381',
    name: 'Standard Specification for Titanium and Titanium Alloy Forgings',
    description: 'Covers titanium and titanium alloy forgings for general industrial use.',
    productTypes: ['Forgings'],
  },
  {
    id: 's5',
    slug: 'ams-4928',
    code: 'AMS 4928',
    name: 'Titanium Alloy Bars, Billets, and Rings 6Al-4V',
    description: 'Aerospace Material Specification for Ti-6Al-4V bar, billet and rings.',
    productTypes: ['Bar', 'Billet', 'Ring'],
  },
]

export const featuredProducts: Product[] = [
  {
    id: 'p1',
    slug: 'grade-2-titanium-round-bar',
    name: 'Grade 2 Titanium Round Bar',
    shortDescription: 'CP titanium round bar per ASTM B348. Diameter 3mm–300mm. Cut-to-size available.',
    category: productCategories[0],
    grades: [titaniumGrades[1]],
    standards: [standards[0]],
    specs: [
      { label: 'Diameter', value: '3 – 300', unit: 'mm' },
      { label: 'Length', value: 'Up to 6000', unit: 'mm' },
      { label: 'Tolerance', value: 'h9 / h11' },
      { label: 'Surface', value: 'Turned, Ground, Polished' },
    ],
    images: [
      {
        id: 'pm1',
        url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
        alt: 'Grade 2 Titanium Round Bar',
        mimeType: 'image/jpeg',
        size: 0,
        filename: 'gr2-round-bar.jpg',
      },
    ],
    featured: true,
    inStock: true,
  },
  {
    id: 'p2',
    slug: 'grade-5-titanium-plate',
    name: 'Grade 5 Ti-6Al-4V Plate',
    shortDescription: 'High-strength Ti-6Al-4V plate per ASTM B265. Thickness 1mm–100mm.',
    category: productCategories[1],
    grades: [titaniumGrades[2]],
    standards: [standards[1]],
    specs: [
      { label: 'Thickness', value: '1 – 100', unit: 'mm' },
      { label: 'Width', value: 'Up to 2000', unit: 'mm' },
      { label: 'Length', value: 'Up to 6000', unit: 'mm' },
      { label: 'Surface', value: 'Mill finish, Annealed' },
    ],
    images: [
      {
        id: 'pm2',
        url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&q=80',
        alt: 'Grade 5 Titanium Plate',
        mimeType: 'image/jpeg',
        size: 0,
        filename: 'gr5-plate.jpg',
      },
    ],
    featured: true,
    inStock: true,
  },
  {
    id: 'p3',
    slug: 'grade-2-titanium-seamless-tube',
    name: 'Grade 2 Titanium Seamless Tube',
    shortDescription: 'CP titanium seamless tube per ASTM B338. OD 6mm–219mm. Heat exchanger grade.',
    category: productCategories[2],
    grades: [titaniumGrades[1]],
    standards: [standards[2]],
    specs: [
      { label: 'OD', value: '6 – 219', unit: 'mm' },
      { label: 'Wall Thickness', value: '0.5 – 10', unit: 'mm' },
      { label: 'Length', value: 'Up to 12000', unit: 'mm' },
      { label: 'Type', value: 'Seamless, Welded' },
    ],
    images: [
      {
        id: 'pm3',
        url: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&q=80',
        alt: 'Titanium Seamless Tube',
        mimeType: 'image/jpeg',
        size: 0,
        filename: 'gr2-tube.jpg',
      },
    ],
    featured: true,
    inStock: true,
  },
]

export const articles: Article[] = [
  {
    id: 'a1',
    slug: 'titanium-grade-guide',
    title: 'Complete Guide to Titanium Grades: Gr.1 to Gr.23',
    excerpt: 'Understand the differences between commercially pure and alloyed titanium grades, their properties and best applications.',
    category: 'Technical Guide',
    tags: ['grades', 'properties', 'selection'],
    publishedAt: '2026-03-15',
    readingTime: 12,
    coverImage: {
      id: 'am1',
      url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80',
      alt: 'Titanium Grade Guide',
      mimeType: 'image/jpeg',
      size: 0,
      filename: 'grade-guide.jpg',
    },
  },
  {
    id: 'a2',
    slug: 'astm-b348-titanium-bar-standard',
    title: 'ASTM B348 Titanium Bar: What Buyers Need to Know',
    excerpt: 'A practical guide to ASTM B348 requirements, grade options, tolerances and documentation for titanium bar procurement.',
    category: 'Standards',
    tags: ['ASTM', 'B348', 'bar', 'procurement'],
    publishedAt: '2026-02-28',
    readingTime: 8,
    coverImage: {
      id: 'am2',
      url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
      alt: 'ASTM B348 Titanium Bar',
      mimeType: 'image/jpeg',
      size: 0,
      filename: 'astm-b348.jpg',
    },
  },
  {
    id: 'a3',
    slug: 'titanium-corrosion-resistance',
    title: 'Titanium Corrosion Resistance: Why It Outperforms Stainless Steel',
    excerpt: 'Explore the corrosion mechanisms that make titanium the material of choice for chemical processing, marine and desalination.',
    category: 'Technical Guide',
    tags: ['corrosion', 'chemical processing', 'marine'],
    publishedAt: '2026-02-10',
    readingTime: 10,
    coverImage: {
      id: 'am3',
      url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&q=80',
      alt: 'Titanium Corrosion Resistance',
      mimeType: 'image/jpeg',
      size: 0,
      filename: 'corrosion.jpg',
    },
  },
]

export const mockDashboard = {
  todayRfqs: 3,
  newRfqs: 12,
  needFollowUp: 5,
  pendingTranslation: 8,
  publishedProducts: 86,
  rfqTrend: [4, 6, 3, 8, 5, 9, 7, 11, 6, 8, 12, 10],
  rfqByCountry: [
    { country: 'United States', count: 28 },
    { country: 'Germany', count: 19 },
    { country: 'India', count: 15 },
    { country: 'South Korea', count: 12 },
    { country: 'Japan', count: 10 },
    { country: 'Others', count: 36 },
  ],
  rfqByProduct: [
    { product: 'Titanium Bar', count: 34 },
    { product: 'Titanium Sheet', count: 28 },
    { product: 'Titanium Tube', count: 22 },
    { product: 'CNC Parts', count: 18 },
    { product: 'Forgings', count: 10 },
    { product: 'Others', count: 8 },
  ],
}
